name       : xgamma
version    : 1.0.6
release    : 8
source     :
    - https://www.x.org/releases/individual/app/xgamma-1.0.6.tar.gz : 66da1d67e84146518b69481c6283c5d8f1027ace9ff7e214d3f81954842e796a
license    : MIT
component  : xorg.apps
summary    : |
    X.Org Applications: xgamma
description: |
    X.Org Applications: xgamma
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xxf86vm)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
